---
title: "Recaudacion Peajes Cordoba"
author: "Patricio del Boca"
date: "August 19, 2016"
output: html_document
layout: post
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(reshape2)
library(lubridate)
library(ggplot2)
library(ggthemes)
```

# Asumptions
 - 2016 es igual al 2015


```{r}
dfPrecio <- read.csv('./data/recaudacion-peajes-cordoba/precio_peajes.csv',
                     dec=",", stringsAsFactors = FALSE)
dfPrecio$Ruta <- tolower(dfPrecio$Ruta)
colnames(dfPrecio) <- c("ruta", "2013", "2014", "2015", "2016")

dfPeajes <- read.csv('./data/recaudacion-peajes-cordoba/transito_peajes.csv',
                     dec=",")
colnames(dfPeajes) <- c("mes", "total", "ruta 20", "ruta 5", "ruta 36 bower",
                        "ruta 9 sur", "autopista cba-pilar", "ruta 19", "ruta 9 norte",
                        "ruta e-53", "ruta e-55")
dfPeajes$mes <- ymd(dfPeajes$mes)


dfPeajes <- dfPeajes %>% 
  select(-total) %>% 
  melt(id.vars="mes") %>%  
  mutate(anio = year(mes)) %>% 
  rename(ruta=variable)

dfPrecio <- dfPrecio %>% 
  melt() %>% 
  rename(anio=variable)
dfPrecio$anio <- as.numeric(as.character(dfPrecio$anio))
dfPeajes$ruta <- as.character(dfPeajes$ruta)

df <- merge(dfPeajes, dfPrecio, by = c("ruta", "anio"))
colnames(df) <- c("ruta", "anio", "mes", "cantidad_autos", "precio")
df$recaudacion <- df$cantidad_autos * df$precio
```

```{r}
ggplot(df[df$ruta=="ruta 20", ], aes(x=mes)) +
  geom_line(aes(y=recaudacion)) + theme_fivethirtyeight()

ggplot(df, aes(x=mes)) +
  geom_line(aes(y=cantidad_autos, group=ruta, colour=ruta)) +
  theme_fivethirtyeight()

df  %>% filter(anio < 2016)  %>% group_by(mes)  %>% summarise(total = sum(cantidad_autos))  %>% plot(type='line')

df  %>% filter(anio < 2016)  %>% group_by(mes)  %>% summarise(total = sum(recaudacion))  %>% plot(type='line')
```

