---
title: "Indice de Precios de Cordoba"
author: "Patricio del Boca"
date: "August 2, 2016"
output: html_document
layout: post
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lubridate)
library(dplyr)
```

## Datos IPC Córdoba
```{r}
# http://estadistica.cba.gov.ar/Publicaciones/InformesEcon%C3%B3micos/tabid/896/language/es-AR/Default.aspx
df <- read.csv('./data/ipc_cordoba_acumulado.csv', stringsAsFactors = FALSE)
df$variacion <- gsub(',','.',df$variacion)
df$variacion <- as.numeric(df$variacion) * 100
df$variacion <- round(df$variacion, 2)
df$mes <- ymd(df$mes)
df$metrica <- "Inflacion"

# http://www.lanacion.com.ar/1864705-la-inflacion-de-san-luis-nueva-referencia-del-gobierno-subio-65
dfSL <- read.csv('./data/ipc_sanluis_acumulado.csv', stringsAsFactors = FALSE)
dfSL <- dfSL[,2:3]
names(dfSL) <- c("valor", "mes")
dfSL$variacion <- gsub(",",".",dfSL$variacion)
dfSL$variacion <- as.numeric(dfSL$variacion)
dfSL$mes <- ymd(dfSL$mes)
```

## Datos Paritarias
```{r}
par <- data.frame()
# http://www.ambito.com/diario/533729-en-paritarias-promedio-de-aumentos-alcanzo-el-26
par <- rbind(par, c(2010, 26))
# http://www.iprofesional.com/notas/118935-Paritarias-en-2011-los-aumentos-ascendieron-a-283-en-promedio-
par <- rbind(par, c(2011, 28.3))
# http://www.ambito.com/diario/640796-alivio-las-paritarias-cierran-con-24-de-tope
par <- rbind(par, c(2012, 25.5))
# http://www.elciudadanoweb.com/el-numero-clave-de-las-paritarias-2013-es-el-24/
par <- rbind(par, c(2013,24))
# http://www.diaadia.com.ar/cordoba/mayoria-gremios-cerraron-paritarias-30-ciento
par <- rbind(par, c(2014,30))
# http://www.lanacion.com.ar/1794407-anuncian-subas-salariales-del-27-promedio-para-cinco-gremios
par <- rbind(par, c(2015,27))
names(par) <- c("anio","aumento")
par$metrica <- "Paritaria"
```


## Inflacion Mensual para Córdoba desde 1968
```{r echo=FALSE}
ggplot(df, aes(x=mes, y=variacion)) + geom_line()
```

```{r}
tmp2 <- df %>% 
  filter(year(mes) %in% c(2010:2015)) %>% 
  slice(1:70) %>% 
  group_by(anio = year(mes)) %>% 
  summarise(acc = sum(variacion))
tmp2$metrica <- "Inflacion"
par$metrica <- "Paritaria"
```
```{r}
ggplot(tmp2, aes(x=anio))
```


```{r}
dataPlot <- rbind(tmp2,par)
ggplot(tmp2, aes(x=anio, y=acc)) +
  geom_bar(stat="identity", fill="steelblue", width=.7) + 
  geom_text(aes(x=anio, y=acc), label = paste0(tmp2$acc,"%"), vjust=-0.4) +
  geom_point(data = par, aes(x=anio,y=aumento), color="red", show.legend = TRUE, shape=) +
  #geom_label(label=paste0(tmp2$acc,"%")) +
  ggtitle("Inflación Anual vs Acuerdo Paritario Promedio.")  + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 30, hjust = 1.1, vjust = 1.8),
        axis.text.y = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank()
        ) 
```

